CREATE TABLE Students (
    StudentID int primary key,
    FirstName varchar(255),
    LastName varchar(255),
    TechSkill1 varchar(255),
    TechSkill1Weight int (1),
    TechSkill2 varchar(255),
    TechSkill2Weight int (1),
    TechSkill3 varchar(255),
    TechSkill3Weight int (1),
    TechSkill4 varchar(255),
    TechSkill4Weight int (1),
    TechSkill5 varchar(255),
    TechSkill5Weight int (1),
    SoftSkill1 varchar(255),
    SoftSkill1Weight int (1),
    SoftSkill2 varchar(255),
    SoftSkill2Weight int (1),
    SoftSkill3 varchar(255),
    SoftSkill3Weight int (1),
    SoftSkill4 varchar(255),
    SoftSkill4Weight int (1),
    SoftSkill5 varchar(255),
    SoftSkill5Weight int (1),
);

